Repository Lazy-Board/BackEnd, pull requests merged in 2023-02, with the labels that each got.

#2 #1 Weather 기본 structure 구현
  .gitignore
  .gradle/7.6/checksums/checksums.lock
  .gradle/7.6/checksums/md5-checksums.bin
  .gradle/7.6/checksums/sha1-checksums.bin
  .gradle/7.6/dependencies-accessors/dependencies-accessors.lock
  .gradle/7.6/dependencies-accessors/gc.properties
  .gradle/7.6/executionHistory/executionHistory.lock
  .gradle/7.6/fileChanges/last-build.bin
  .gradle/7.6/fileHashes/fileHashes.lock
  .gradle/7.6/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/vcs-1/gc.properties
  build.gradle
  src/main/java/com/example/lazier/WeatherModule/dto/UserWeatherDto.java
  src/main/java/com/example/lazier/WeatherModule/dto/WeatherDto.java
  src/main/java/com/example/lazier/WeatherModule/model/UserWeatherInput.java
  src/main/java/com/example/lazier/WeatherModule/persist/entity/UserWeather.java
  src/main/java/com/example/lazier/WeatherModule/persist/entity/Weather.java
  src/main/java/com/example/lazier/WeatherModule/persist/repository/UserWeatherRepository.java
  src/main/java/com/example/lazier/WeatherModule/persist/repository/WeatherRepository.java
  src/main/resources/application.yml
Labels: enhancement

#4 #3 Scraping 을 위한 scraper 구현
  src/main/java/com/example/lazier/WeatherModule/dto/UserWeatherDto.java
  src/main/java/com/example/lazier/WeatherModule/persist/entity/Weather.java
  src/main/java/com/example/lazier/WeatherModule/scraper/Impl/NaverWeatherScraper.java
  src/main/java/com/example/lazier/WeatherModule/scraper/Scraper.java
Labels: enhancement

#6 Youtube_Feat: #5 - YoutubeScrapper 구현
  .gitignore
  .gradle/7.6/checksums/checksums.lock
  .gradle/7.6/checksums/md5-checksums.bin
  .gradle/7.6/checksums/sha1-checksums.bin
  .gradle/7.6/dependencies-accessors/dependencies-accessors.lock
  .gradle/7.6/dependencies-accessors/gc.properties
  .gradle/7.6/executionHistory/executionHistory.bin
  .gradle/7.6/executionHistory/executionHistory.lock
  .gradle/7.6/fileChanges/last-build.bin
  .gradle/7.6/fileHashes/fileHashes.bin
  .gradle/7.6/fileHashes/fileHashes.lock
  .gradle/7.6/fileHashes/resourceHashesCache.bin
  .gradle/7.6/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  .gradle/vcs-1/gc.properties
  build.gradle
  src/main/java/com/example/lazier/LazierApplication.java
  src/main/java/com/example/lazier/YoutubeModule/config/SchedulerConfig.java
  src/main/java/com/example/lazier/YoutubeModule/model/ScrapedResult.java
  src/main/java/com/example/lazier/YoutubeModule/model/Youtube.java
  src/main/java/com/example/lazier/YoutubeModule/persist/entity/YoutubeEntity.java
  src/main/java/com/example/lazier/YoutubeModule/persist/repository/YoutubeRepository.java
  src/main/java/com/example/lazier/YoutubeModule/scheduler/ScraperScheduler.java
  src/main/java/com/example/lazier/YoutubeModule/scrapper/YoutubeScrapper.java
  src/main/java/com/example/lazier/YoutubeModule/service/YoutubeService.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: enhancement

#10 Weather_Feat: #8 - 유저정보 controller, service 구현
  .gradle/7.6/executionHistory/executionHistory.bin
  .gradle/7.6/executionHistory/executionHistory.lock
  .gradle/7.6/fileHashes/fileHashes.bin
  .gradle/7.6/fileHashes/fileHashes.lock
  .gradle/7.6/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  src/main/java/com/example/lazier/WeatherModule/controller/UserWeatherController.java
  src/main/java/com/example/lazier/WeatherModule/persist/entity/UserWeather.java
  src/main/java/com/example/lazier/WeatherModule/service/Impl/UserWeatherServiceImpl.java
  src/main/java/com/example/lazier/WeatherModule/service/UserWeatherService.java
Labels: enhancement

#15 #9, #13 Member token
  .gitignore
  build.gradle
  src/main/java/com/example/lazier/LazierApplication.java
  src/main/java/com/example/lazier/user/component/MailComponents.java
  src/main/java/com/example/lazier/user/controller/MemberController.java
  src/main/java/com/example/lazier/user/dto/AccessTokenDTO.java
  src/main/java/com/example/lazier/user/dto/JoinDTO.java
  src/main/java/com/example/lazier/user/dto/TokenDTO.java
  src/main/java/com/example/lazier/user/entity/LazierUser.java
  src/main/java/com/example/lazier/user/entity/RefreshToken.java
  src/main/java/com/example/lazier/user/enums/UserRole.java
  src/main/java/com/example/lazier/user/enums/UserStatus.java
  src/main/java/com/example/lazier/user/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/example/lazier/user/exception/CustomerExceptionHandler.java
  src/main/java/com/example/lazier/user/exception/ErrorMessage.java
  src/main/java/com/example/lazier/user/exception/FailedLoginException.java
  src/main/java/com/example/lazier/user/exception/FailedSignUpException.java
  src/main/java/com/example/lazier/user/exception/NotFoundMemberException.java
  src/main/java/com/example/lazier/user/exception/NotMatchMemberException.java
  src/main/java/com/example/lazier/user/exception/UnauthorizedMemberException.java
  src/main/java/com/example/lazier/user/exception/UnauthorizedRefreshTokenException.java
  src/main/java/com/example/lazier/user/model/UserLogin.java
  src/main/java/com/example/lazier/user/model/UserSignUp.java
  src/main/java/com/example/lazier/user/repository/RefreshTokenRepository.java
  src/main/java/com/example/lazier/user/repository/UserRepository.java
  src/main/java/com/example/lazier/user/security/JwtFilter.java
  src/main/java/com/example/lazier/user/security/JwtService.java
  src/main/java/com/example/lazier/user/security/JwtTokenProvider.java
  src/main/java/com/example/lazier/user/security/SecurityConfig.java
  src/main/java/com/example/lazier/user/service/join/JoinService.java
  src/main/java/com/example/lazier/user/service/join/JoinServicelmpl.java
  src/main/java/com/example/lazier/user/service/login/CreateTokenService.java
  src/main/java/com/example/lazier/user/service/login/CreateTokenServiceImpl.java
  src/main/java/com/example/lazier/user/service/login/LoginService.java
  src/main/java/com/example/lazier/user/service/login/LoginServiceImpl.java
  src/main/resources/application.properties
Labels: enhancement

#23 Weather_Feat: #12 - 날씨 controller, service 구현
  .gradle/7.6/executionHistory/executionHistory.bin
  .gradle/7.6/executionHistory/executionHistory.lock
  .gradle/7.6/fileHashes/fileHashes.bin
  .gradle/7.6/fileHashes/fileHashes.lock
  .gradle/7.6/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  src/main/java/com/example/lazier/WeatherModule/controller/WeatherController.java
  src/main/java/com/example/lazier/WeatherModule/dto/WeatherDto.java
  src/main/java/com/example/lazier/WeatherModule/persist/repository/WeatherRepository.java
  src/main/java/com/example/lazier/WeatherModule/service/Impl/UserWeatherServiceImpl.java
  src/main/java/com/example/lazier/WeatherModule/service/Impl/WeatherServiceImpl.java
  src/main/java/com/example/lazier/WeatherModule/service/WeatherService.java
Labels: enhancement

#17 Exchange_Feat: #16 - Scraper 기능 추가
  src/main/java/com/example/lazier/exchangeModule/scheduler/ScraperScheduler.java
  src/main/java/com/example/lazier/exchangeModule/scraper/Scraper.java
Labels: enhancement

#19 Exchange_Feat_CRUD: #18 - 환율 서비스 CRUD 기능 구현
  src/main/java/com/example/lazier/exchangeModule/controller/ExchangeController.java
  src/main/java/com/example/lazier/exchangeModule/dto/ExchangeDto.java
  src/main/java/com/example/lazier/exchangeModule/persist/entity/Exchange.java
  src/main/java/com/example/lazier/exchangeModule/persist/repository/ExchangeRepository.java
  src/main/java/com/example/lazier/exchangeModule/service/ExchangeService.java
  src/main/java/com/example/lazier/exchangeModule/service/ExchangeServiceImpl.java
Labels: enhancement

#21 Exchange_Feat_Partial-CRUD: #20 - 부분 환율 서비스 CRUD 기능 구현
  src/main/java/com/example/lazier/exchangeModule/dto/PartialExchangeDto.java
  src/main/java/com/example/lazier/exchangeModule/persist/entity/PartialExchange.java
  src/main/java/com/example/lazier/exchangeModule/persist/repository/PartialExchangeRepository.java
  src/main/java/com/example/lazier/exchangeModule/scraper/ExchangeScraper.java
  src/main/java/com/example/lazier/exchangeModule/service/PartialExchangeService.java
  src/main/java/com/example/lazier/exchangeModule/service/PartialExchangeServiceImpl.java
Labels: enhancement

#25 Quotes_Feat: #24 - 명언 구현
  build.gradle
  src/main/java/com/example/lazier/QuotesModule/controller/QuotesController.java
  src/main/java/com/example/lazier/QuotesModule/dto/QuotesDto.java
  src/main/java/com/example/lazier/QuotesModule/persist/entity/Quotes.java
  src/main/java/com/example/lazier/QuotesModule/persist/repository/QuotesRepository.java
  src/main/java/com/example/lazier/QuotesModule/service/Impl/QuotesServiceImpl.java
  src/main/java/com/example/lazier/QuotesModule/service/QuotesService.java
Labels: enhancement

#31 Quotes_Feat: #28 - 사용자 문구
  build.gradle
  src/main/java/com/example/lazier/QuotesModule/controller/UserQuotesController.java
  src/main/java/com/example/lazier/QuotesModule/dto/UserQuotesDto.java
  src/main/java/com/example/lazier/QuotesModule/model/UserQuotesInput.java
  src/main/java/com/example/lazier/QuotesModule/persist/entity/UserQuotes.java
  src/main/java/com/example/lazier/QuotesModule/persist/repository/UserQuotesRepository.java
  src/main/java/com/example/lazier/QuotesModule/service/Impl/UseQuotesServiceImpl.java
  src/main/java/com/example/lazier/QuotesModule/service/UserQuoteService.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: enhancement

#35 Stock_Feat: #34 - 주식 스크래핑 작업 완료
  build.gradle
  src/main/java/com/example/lazier/stockModule/persist/entity/Kosdac.java
  src/main/java/com/example/lazier/stockModule/persist/entity/Kospi.java
  src/main/java/com/example/lazier/stockModule/scraper/KosdacScraper.java
  src/main/java/com/example/lazier/stockModule/scraper/KospiScraper.java
  src/main/java/com/example/lazier/stockModule/scraper/NaverKosdacScraper.java
  src/main/java/com/example/lazier/stockModule/scraper/NaverKospiScraper.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: enhancement

#36 Weather_Feat: #33 - 날씨 scheduler, exception handler 구현
  src/main/java/com/example/lazier/LazierApplication.java
  src/main/java/com/example/lazier/WeatherModule/controller/UserWeatherController.java
  src/main/java/com/example/lazier/WeatherModule/controller/WeatherController.java
  src/main/java/com/example/lazier/WeatherModule/exception/AddressNotFoundException.java
  src/main/java/com/example/lazier/WeatherModule/exception/ErrorMessage.java
  src/main/java/com/example/lazier/WeatherModule/exception/UserAlreadyExistException.java
  src/main/java/com/example/lazier/WeatherModule/exception/UserNotFoundException.java
  src/main/java/com/example/lazier/WeatherModule/exception/handler/UserWeatherExceptionHandler.java
  src/main/java/com/example/lazier/WeatherModule/exception/handler/WeatherExceptionHandler.java
  src/main/java/com/example/lazier/WeatherModule/scheduler/ScraperScheduler.java
  src/main/java/com/example/lazier/WeatherModule/scraper/Impl/NaverWeatherScraper.java
  src/main/java/com/example/lazier/WeatherModule/service/Impl/UserWeatherServiceImpl.java
  src/main/java/com/example/lazier/WeatherModule/service/Impl/WeatherServiceImpl.java
  src/main/java/com/example/lazier/WeatherModule/service/UserWeatherService.java
  src/main/java/com/example/lazier/WeatherModule/service/WeatherService.java
  src/main/resources/application.yml
Labels: enhancement

#37 Member_Feat: #22 - redis 설정 및 로그인 리팩토링
  build.gradle
  src/main/java/com/example/lazier/user/config/RedisConfig.java
  src/main/java/com/example/lazier/user/controller/MemberController.java
  src/main/java/com/example/lazier/user/dto/AccessTokenDto.java
  src/main/java/com/example/lazier/user/dto/JoinDto.java
  src/main/java/com/example/lazier/user/dto/TokenDto.java
  src/main/java/com/example/lazier/user/entity/RefreshToken.java
  src/main/java/com/example/lazier/user/exception/CustomerExceptionHandler.java
  src/main/java/com/example/lazier/user/exception/InvalidTokenException.java
  src/main/java/com/example/lazier/user/model/UserLoginInput.java
  src/main/java/com/example/lazier/user/model/UserSignupInput.java
  src/main/java/com/example/lazier/user/repository/RefreshTokenRepository.java
  src/main/java/com/example/lazier/user/security/JwtFilter.java
  src/main/java/com/example/lazier/user/security/JwtService.java
  src/main/java/com/example/lazier/user/security/JwtTokenProvider.java
  src/main/java/com/example/lazier/user/security/SecurityConfig.java
  src/main/java/com/example/lazier/user/service/CreateTokenService.java
  src/main/java/com/example/lazier/user/service/JoinService.java
  src/main/java/com/example/lazier/user/service/LoginService.java
  src/main/java/com/example/lazier/user/service/RedisService.java
  src/main/java/com/example/lazier/user/service/join/JoinService.java
  src/main/java/com/example/lazier/user/service/login/CreateTokenService.java
  src/main/java/com/example/lazier/user/service/login/CreateTokenServiceImpl.java
  src/main/java/com/example/lazier/user/service/login/LoginService.java
  src/main/java/com/example/lazier/user/service/login/LoginServiceImpl.java
Labels: enhancement

#40 Weather_Feat: #39 - swagger 적용
  build.gradle
  src/main/java/com/example/lazier/WeatherModule/config/SwaggerConfig.java
  src/main/java/com/example/lazier/WeatherModule/controller/UserWeatherController.java
  src/main/java/com/example/lazier/WeatherModule/controller/WeatherController.java
  src/main/java/com/example/lazier/WeatherModule/scraper/Impl/NaverWeatherScraper.java
  src/main/resources/application.properties
Labels: enhancement

#42 Quotes_Feat: #41 - Exception
  src/main/java/com/example/lazier/QuotesModule/exception/ErrorMessage.java
  src/main/java/com/example/lazier/QuotesModule/exception/UserAlreadyExistException.java
  src/main/java/com/example/lazier/QuotesModule/exception/UserNotFoundException.java
  src/main/java/com/example/lazier/QuotesModule/exception/WrongIdNumberException.java
  src/main/java/com/example/lazier/QuotesModule/exception/handler/QuotesExceptionHandler.java
  src/main/java/com/example/lazier/QuotesModule/exception/handler/UserQuotesExceptionHandler.java
  src/main/java/com/example/lazier/QuotesModule/service/Impl/QuotesServiceImpl.java
  src/main/java/com/example/lazier/QuotesModule/service/Impl/UseQuotesServiceImpl.java
Labels: enhancement

#44 Member_Feat: #38 - oauth google
  .gitignore
  build.gradle
  src/main/java/com/example/lazier/user/config/JasyptConfig.java
  src/main/java/com/example/lazier/user/config/JwtFilter.java
  src/main/java/com/example/lazier/user/config/JwtTokenProvider.java
  src/main/java/com/example/lazier/user/config/SecurityConfig.java
  src/main/java/com/example/lazier/user/controller/MemberController.java
  src/main/java/com/example/lazier/user/dto/GoogleUserDto.java
  src/main/java/com/example/lazier/user/dto/OAuthTokenDto.java
  src/main/java/com/example/lazier/user/entity/LazierUser.java
  src/main/java/com/example/lazier/user/entity/RefreshToken.java
  src/main/java/com/example/lazier/user/enums/UserRole.java
  src/main/java/com/example/lazier/user/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/example/lazier/user/exception/CustomerExceptionHandler.java
  src/main/java/com/example/lazier/user/exception/InvalidAccessException.java
  src/main/java/com/example/lazier/user/repository/UserRepository.java
  src/main/java/com/example/lazier/user/service/CreateTokenService.java
  src/main/java/com/example/lazier/user/service/JoinService.java
  src/main/java/com/example/lazier/user/service/JwtService.java
  src/main/java/com/example/lazier/user/service/OAuthService.java
  src/main/java/com/example/lazier/user/service/RedisService.java
  src/main/resources/application-oauth.yml
Labels: enhancement

#48 Weather_Refactor: #47 - controller annotation
  src/main/java/com/example/lazier/WeatherModule/controller/UserWeatherController.java
Labels: documentation

#46 Quotes_Refactor: #45 - controller annotation 수정
  src/main/java/com/example/lazier/QuotesModule/controller/UserQuotesController.java
Labels: documentation

#49 Youtube_feat : #7 service&controller (Module 기능완성)
  .gradle/7.6/checksums/checksums.lock
  .gradle/7.6/checksums/md5-checksums.bin
  .gradle/7.6/checksums/sha1-checksums.bin
  .gradle/7.6/executionHistory/executionHistory.bin
  .gradle/7.6/executionHistory/executionHistory.lock
  .gradle/7.6/fileHashes/fileHashes.bin
  .gradle/7.6/fileHashes/fileHashes.lock
  .gradle/7.6/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  build.gradle
  scratch_youtube.http
  src/main/java/com/example/lazier/LazierApplication.java
  src/main/java/com/example/lazier/YoutubeModule/config/SchedulerConfig.java
  src/main/java/com/example/lazier/YoutubeModule/controller/YoutubeController.java
  src/main/java/com/example/lazier/YoutubeModule/exception/CustomException.java
  src/main/java/com/example/lazier/YoutubeModule/exception/CustomExceptionHandler.java
  src/main/java/com/example/lazier/YoutubeModule/exception/ErrorResponse.java
  src/main/java/com/example/lazier/YoutubeModule/exception/impl/CustomExceptionEx1.java
  src/main/java/com/example/lazier/YoutubeModule/exception/impl/CustomExceptionEx2.java
  src/main/java/com/example/lazier/YoutubeModule/model/ScrapedResult.java
  src/main/java/com/example/lazier/YoutubeModule/model/Youtube.java
  src/main/java/com/example/lazier/YoutubeModule/persist/entity/YoutubeEntity.java
  src/main/java/com/example/lazier/YoutubeModule/persist/repository/YoutubeRepository.java
  src/main/java/com/example/lazier/YoutubeModule/scheduler/ScraperScheduler.java
  src/main/java/com/example/lazier/YoutubeModule/scrapper/YoutubeScraper.java
  src/main/java/com/example/lazier/YoutubeModule/scrapper/YoutubeScrapper.java
  src/main/java/com/example/lazier/YoutubeModule/service/YoutubeService.java
  src/main/java/com/example/lazier/YoutubeModule/service/YoutubeServiceImpl.java
  src/main/resources/application.yml
Labels: enhancement

#52 Weather_Test: #51 - userWeatherService test
  .gradle/7.6/executionHistory/executionHistory.bin
  .gradle/7.6/executionHistory/executionHistory.lock
  .gradle/7.6/fileHashes/fileHashes.bin
  .gradle/7.6/fileHashes/fileHashes.lock
  .gradle/7.6/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  src/test/java/com/example/lazier/WeatherModule/service/Impl/UserWeatherServiceImplTest.java
Labels: enhancement

#61 Traffic_Feat : #50 - Traffic 모듈
  .gradle/7.6/checksums/checksums.lock
  .gradle/7.6/checksums/md5-checksums.bin
  .gradle/7.6/checksums/sha1-checksums.bin
  build.gradle
  src/main/java/com/example/lazier/component/KakaoNavigationApi.java
  src/main/java/com/example/lazier/component/NaverGeocodingApi.java
  src/main/java/com/example/lazier/controller/traffic/TrafficController.java
  src/main/java/com/example/lazier/dto/traffic/DurationDto.java
  src/main/java/com/example/lazier/dto/traffic/TrafficDto.java
  src/main/java/com/example/lazier/dto/traffic/TrafficInput.java
  src/main/java/com/example/lazier/exception/WrongAddressFormException.java
  src/main/java/com/example/lazier/exception/traffic/TrafficExceptionHandler.java
  src/main/java/com/example/lazier/persist/entity/traffic/Traffic.java
  src/main/java/com/example/lazier/persist/repository/traffic/TrafficRepository.java
  src/main/java/com/example/lazier/service/traffic/TrafficService.java
  src/main/resources/application.yml
Labels: enhancement

#65 Stock_feat_refactor: #64 - 코드 리팩토링
  src/main/java/com/example/lazier/stockModule/controller/StockController.java
  src/main/java/com/example/lazier/stockModule/exception/UserAlreadyExistException.java
  src/main/java/com/example/lazier/stockModule/exception/UserNotFoundException.java
  src/main/java/com/example/lazier/stockModule/service/Impl/UserStockServiceImpl.java
  src/main/java/com/example/lazier/stockModule/service/UserStockService.java
Labels: enhancement

#75 Weather_refactor #74 - weather 모듈 리펙토링
  .gradle/7.6/executionHistory/executionHistory.bin
  .gradle/7.6/executionHistory/executionHistory.lock
  .gradle/7.6/fileHashes/fileHashes.bin
  .gradle/7.6/fileHashes/fileHashes.lock
  .gradle/7.6/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  src/main/java/com/example/lazier/config/user/SecurityConfig.java
  src/main/java/com/example/lazier/controller/UserWeatherController.java
  src/main/java/com/example/lazier/controller/WeatherController.java
  src/main/java/com/example/lazier/dto/module/UserWeatherDto.java
  src/main/java/com/example/lazier/dto/module/UserWeatherInput.java
  src/main/java/com/example/lazier/dto/module/WeatherDto.java
  src/main/java/com/example/lazier/persist/entity/module/UserWeather.java
  src/main/java/com/example/lazier/persist/entity/module/Weather.java
  src/main/java/com/example/lazier/persist/entity/user/LazierUser.java
  src/main/java/com/example/lazier/persist/repository/UserWeatherRepository.java
  src/main/java/com/example/lazier/persist/repository/WeatherRepository.java
  src/main/java/com/example/lazier/scheduler/ScraperScheduler.java
  src/main/java/com/example/lazier/scraper/NaverWeatherScraper.java
  src/main/java/com/example/lazier/service/Impl/UserWeatherService.java
  src/main/java/com/example/lazier/service/Impl/WeatherService.java
  src/main/java/com/example/lazier/service/UserWeatherService.java
  src/main/java/com/example/lazier/service/WeatherService.java
  src/test/java/com/example/lazier/service/Impl/UserWeatherServiceImplTest.java
Labels: documentation

#77 Traffic_refactor #76 - refactoring
  .gradle/7.6/executionHistory/executionHistory.bin
  .gradle/7.6/executionHistory/executionHistory.lock
  .gradle/7.6/fileHashes/fileHashes.bin
  .gradle/7.6/fileHashes/fileHashes.lock
  .gradle/7.6/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  src/main/java/com/example/lazier/dto/traffic/TrafficDto.java
  src/main/java/com/example/lazier/dto/traffic/TrafficInput.java
  src/main/java/com/example/lazier/persist/entity/traffic/Traffic.java
  src/main/java/com/example/lazier/persist/repository/traffic/TrafficRepository.java
  src/main/java/com/example/lazier/service/traffic/TrafficService.java
  src/main/resources/application.yml
Labels: documentation

#87 News&Youtube_Fix: Swagger-Ui 적용
  .gitignore
  .gradle/7.6/checksums/checksums.lock
  .gradle/7.6/executionHistory/executionHistory.bin
  .gradle/7.6/executionHistory/executionHistory.lock
  .gradle/7.6/fileHashes/fileHashes.bin
  .gradle/7.6/fileHashes/fileHashes.lock
  .gradle/7.6/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  build.gradle
  src/main/java/com/example/lazier/config/SwaggerConfig.java
  src/main/java/com/example/lazier/config/module/SwaggerConfig.java
  src/main/java/com/example/lazier/config/user/SecurityConfig.java
  src/main/java/com/example/lazier/controller/NewsController.java
  src/main/java/com/example/lazier/controller/NewsUserController.java
  src/main/java/com/example/lazier/controller/YoutubeController.java
Labels: documentation

#88 HotFix_Traffic, Quotes, Weather @Transactional 추가, 폴더 변경 및 그외 어노테이션 추가
  .gradle/7.6/executionHistory/executionHistory.bin
  .gradle/7.6/executionHistory/executionHistory.lock
  .gradle/7.6/fileHashes/fileHashes.bin
  .gradle/7.6/fileHashes/fileHashes.lock
  .gradle/7.6/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  src/main/java/com/example/lazier/controller/QuotesController.java
  src/main/java/com/example/lazier/controller/TrafficController.java
  src/main/java/com/example/lazier/controller/UserQuotesController.java
  src/main/java/com/example/lazier/controller/UserWeatherController.java
  src/main/java/com/example/lazier/controller/WeatherController.java
  src/main/java/com/example/lazier/dto/module/DurationDto.java
  src/main/java/com/example/lazier/dto/module/QuotesDto.java
  src/main/java/com/example/lazier/dto/module/TrafficInput.java
  src/main/java/com/example/lazier/dto/module/UserQuotesDto.java
  src/main/java/com/example/lazier/dto/module/UserQuotesInput.java
  src/main/java/com/example/lazier/dto/module/UserWeatherDto.java
  src/main/java/com/example/lazier/dto/module/UserWeatherInput.java
  src/main/java/com/example/lazier/service/module/TrafficService.java
  src/main/java/com/example/lazier/service/module/UserQuotesService.java
  src/main/java/com/example/lazier/service/module/UserWeatherService.java
Labels: bug

#90 HotFix_Traffic, Quotes, Weather fix
  src/main/java/com/example/lazier/service/module/TrafficService.java
  src/main/java/com/example/lazier/service/module/UserQuotesService.java
  src/main/java/com/example/lazier/service/module/UserWeatherService.java
  src/main/java/com/example/lazier/service/module/WeatherService.java
Labels: bug

#91 Weather_fix : 날씨 모듈 수정
  src/main/java/com/example/lazier/persist/repository/WeatherRepository.java
  src/main/java/com/example/lazier/scheduler/WeatherScraperScheduler.java
  src/main/java/com/example/lazier/scraper/NaverWeatherScraper.java
  src/main/java/com/example/lazier/service/module/WeatherService.java
Labels: bug

#94 1. *Fix* : ALL CONTROLLER
  .gradle/7.6/executionHistory/executionHistory.bin
  .gradle/7.6/executionHistory/executionHistory.lock
  .gradle/7.6/fileHashes/fileHashes.bin
  .gradle/7.6/fileHashes/fileHashes.lock
  .gradle/7.6/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  scratch_news.http
  src/main/java/com/example/lazier/config/user/SecurityConfig.java
  src/main/java/com/example/lazier/controller/ExchangeController.java
  src/main/java/com/example/lazier/controller/MemberController.java
  src/main/java/com/example/lazier/controller/NewsController.java
  src/main/java/com/example/lazier/controller/NewsUserController.java
  src/main/java/com/example/lazier/controller/QuotesController.java
  src/main/java/com/example/lazier/controller/StockController.java
  src/main/java/com/example/lazier/controller/TodoController.java
  src/main/java/com/example/lazier/controller/TrafficController.java
  src/main/java/com/example/lazier/controller/UserQuotesController.java
  src/main/java/com/example/lazier/controller/UserWeatherController.java
  src/main/java/com/example/lazier/controller/WeatherController.java
  src/main/java/com/example/lazier/controller/YoutubeController.java
  src/main/java/com/example/lazier/dto/module/NewsDto.java
  src/main/java/com/example/lazier/dto/module/NewsUserInput.java
  src/main/java/com/example/lazier/persist/entity/module/News.java
  src/main/java/com/example/lazier/persist/repository/NewsPressRepository.java
  src/main/java/com/example/lazier/scraper/NewsScraper.java
  src/main/java/com/example/lazier/service/module/NewsService.java
  src/main/java/com/example/lazier/service/module/NewsUserService.java
  src/main/java/com/example/lazier/service/user/JoinService.java
Labels: enhancement
